.TH "mem Directory Reference" 3 "Sat Nov 23 2013" "Version 1.0BetaR01" "eSolid - Memory Management" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mem Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmem\&.h\fP"
.br
.RI "\fIMemory Management API\&. \fP"
.ti -1c
.RI "file \fBmem_cfg\&.h\fP"
.br
.RI "\fIKonfiguracija memorijskog menadzmenta\&. \fP"
.in -1c
