.TH "lit" 3 "Fri Nov 22 2013" "Version 1.0BetaR01" "eSolid - Memory Management" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lit \- Literatura i korisna dokumentacija 

.SH "Literatura"
.PP
.IP "\(bu" 2
IBM predlog koncepta za event processing arhitekturu: 
.br
http://www.ibm.com/developerworks/webservices/library/ws-eventprocessing/index.html
.IP "\(bu" 2
Event-Driven Architecture Overview 
.br
Brenda M\&. Michelson
.IP "\(bu" 2
Tehnicko drustvo za event processing: 
.br
http://www.ep-ts.com/
.IP "\(bu" 2
UML Tutorial: Finite State Machines 
.br
Robert C\&. Martin 
.br
Engineering Notebook Column
.IP "\(bu" 2
Practical UML Statecharts in C/C++ 
.br
Miro Samek
.br
http://www.state-machine.com/psicc2/index.php
.IP "\(bu" 2
Statecharts: A visual formalism for complex systems 
.br
David Harel
.IP "\(bu" 2
Nesos - Finite State Machine Operating System Reference Guide 
.br
Jan Erik Nilsen 
.br
http://www.nilsenelektronikk.no
.IP "\(bu" 2
Object-oriented programming with ANSI-C 
.br
Axel-Tobias Schreiner
.IP "\(bu" 2
Trace Recording for Embedded Systems: Lessons Learned from Five Industrial Projects 
.br
Johan Kraft , Anders Wall and Holger Kienle
.IP "\(bu" 2
Cortex-M3 Technical Reference Manual (TRM): 
.br
 http://infocenter.arm.com/help/topic/com.arm.doc.ddi0337g/index.html
.IP "\(bu" 2
AAPCS Procedure Call Standard for the ARM Architecture: 
.br
http://infocenter.arm.com/help/topic/com.arm.doc.ihi0042c/index.html
.PP
.SH "Preporuceni linkovi"
.PP
.IP "\(bu" 2
Quantum Leaps 
.br
Quantum Leaps, pruza state-machine framework i graficke alate za modeliranje za real time embedded sisteme\&. 
.br
http://www.state-machine.com
.IP "\(bu" 2
BeRTOS is a real time open source operating system 
.br
 BeRTOS je odlican real time OS koji poseduje mnostvo kvalitetnih ideja i koncepta programiranja od kojih se neki koriste i u ovom projektu\&. 
.br
http://www.bertos.org
.IP "\(bu" 2
ChibiOS/RT 
.br
ChibiOS/RT je projektovan za embedded real-time sisteme ciji su zahtevi efikasnost izvrsavanja i kompaktan kod\&. Ovaj RTOS karakterisu visoka portabilnost, kompaktna velicina i arhitektura koja je optimizovana za kratka vremena komutacije procesa\&. 
.br
http://www.chibios.org
.PP
.SH "Srodne alatke i ostali resursi"
.PP
.IP "\(bu" 2
CodeSourcery
.br
Pruza odlican ARM kompajler sa pristojnom dokumentacijom\&. Lite verzija je besplatna\&. 
.br
http://http://www.mentor.com/embedded-software/sourcery-tools/sourcery-codebench/
.IP "\(bu" 2
Yagarto toolchain - Yet another GNU ARM toolchain
.br
 Open source, besplatan ARM set alatki\&. 
.br
http://www.yagarto.de/
.PP
.SH "Stil kodiranja u eSolid-u"
.PP
.IP "\(bu" 2
Stil kodiranja u eSolid-u: 
.br
http://blueskynet.dyndns-server.com/doc/D0020-Stilovi%20kodiranja%20(Software).pdf 
.PP

