.TH "mem.h" 3 "Sat Nov 23 2013" "Version 1.0BetaR01" "eSolid - Memory Management" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mem.h \- 
.PP
Memory Management API\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'arch/compiler\&.h'\fP
.br
\fC#include 'arch/cpu\&.h'\fP
.br
\fC#include 'kernel/dbg\&.h'\fP
.br
\fC#include 'mem/mem_cfg\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBesMemStatus\fP"
.br
.RI "\fIMemory status structure\&. \fP"
.ti -1c
.RI "struct \fBesSMemHandle\fP"
.br
.RI "\fIStatic memory instance handle structure\&. \fP"
.ti -1c
.RI "struct \fBesPMemHandle\fP"
.br
.RI "\fIPool memory instance handle structure\&. \fP"
.ti -1c
.RI "struct \fBesDMemHandle\fP"
.br
.RI "\fIDynamic memory instance handle structure\&. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBesMemStatus\fP \fBesMemStatus_T\fP"
.br
.RI "\fIMemory status type\&. \fP"
.in -1c
.PP
.RI "\fBStatic memory manager - SMem\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "typedef struct \fBesSMemHandle\fP \fBesSMemHandle_T\fP"
.br
.RI "\fIStatic memory instance handle type\&. \fP"
.in -1c
.in -1c
.PP
.RI "\fBPool memory allocator - PMem\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "typedef struct \fBesPMemHandle\fP \fBesPMemHandle_T\fP"
.br
.RI "\fIPool memory instance handle type\&. \fP"
.in -1c
.in -1c
.PP
.RI "\fBDynamic memory allocator - DMem\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "typedef struct \fBesDMemHandle\fP \fBesDMemHandle_T\fP"
.br
.RI "\fIDynamic memory instance handle type\&. \fP"
.in -1c
.in -1c
.SS "Functions"

.PP
.RI "\fBStatic memory manager\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "void \fBesSMemInit\fP (\fBesSMemHandle_T\fP *handle, void *storage, size_t storageSize)"
.br
.RI "\fIInitializes static memory instance\&. \fP"
.ti -1c
.RI "void * \fBesSMemAllocI\fP (\fBesSMemHandle_T\fP *handle, size_t size)"
.br
.RI "\fIAllocates static memory of size \fCsize\fP\&. \fP"
.ti -1c
.RI "void * \fBesSMemAlloc\fP (\fBesSMemHandle_T\fP *handle, size_t size)"
.br
.RI "\fIAllocates static memory of size \fCsize\fP\&. \fP"
.ti -1c
.RI "void \fBesSMemUpdateStatusI\fP (\fBesSMemHandle_T\fP *handle, \fBesMemStatus_T\fP *status)"
.br
.RI "\fIReturns various information about given memory instance\&. \fP"
.ti -1c
.RI "void \fBesSMemUpdateStatus\fP (\fBesSMemHandle_T\fP *handle, \fBesMemStatus_T\fP *status)"
.br
.RI "\fIReturns various information about given memory instance\&. \fP"
.in -1c
.in -1c
.PP
.RI "\fBPool memory manager\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "void \fBesPMemInit\fP (\fBesPMemHandle_T\fP *handle, void *pool, size_t poolSize, size_t blockSize)"
.br
.RI "\fIInitializes pool memory instance\&. \fP"
.ti -1c
.RI "size_t \fBesPMemCalcPoolSize\fP (size_t blocks, size_t blockSize)"
.br
.RI "\fICalculates required reserved memory size for defined number of blocks\&. \fP"
.ti -1c
.RI "void * \fBesPMemAllocI\fP (\fBesPMemHandle_T\fP *handle)"
.br
.RI "\fIAllocate one block from memory pool\&. \fP"
.ti -1c
.RI "void * \fBesPMemAlloc\fP (\fBesPMemHandle_T\fP *handle)"
.br
.RI "\fIAllocate one block from memory pool\&. \fP"
.ti -1c
.RI "void \fBesPMemDeAllocI\fP (\fBesPMemHandle_T\fP *handle, void *mem)"
.br
.RI "\fIOslobadja prethodno alocirani blok\&. \fP"
.ti -1c
.RI "void \fBesPMemDeAlloc\fP (\fBesPMemHandle_T\fP *handle, void *mem)"
.br
.RI "\fIOslobadja prethodno alocirani blok\&. \fP"
.ti -1c
.RI "void \fBesPMemUpdateStatusI\fP (\fBesPMemHandle_T\fP *handle, \fBesMemStatus_T\fP *status)"
.br
.RI "\fIVraca statusne informacije pool memorije\&. \fP"
.ti -1c
.RI "void \fBesPMemUpdateStatus\fP (\fBesPMemHandle_T\fP *handle, \fBesMemStatus_T\fP *status)"
.br
.RI "\fIVraca statusne informacije pool memorije\&. \fP"
.in -1c
.in -1c
.PP
.RI "\fBDynamic memory allocator\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "void \fBesDMemInit\fP (\fBesDMemHandle_T\fP *handle, void *storage, size_t storageSize)"
.br
.RI "\fIInicijalizuje dinamican memorijski alokator\&. \fP"
.ti -1c
.RI "void * \fBesDMemAllocI\fP (\fBesDMemHandle_T\fP *handle, size_t size)"
.br
.RI "\fIDodeljuje memorijski prostor velicine \fCsize\fP\&. \fP"
.ti -1c
.RI "void * \fBesDMemAlloc\fP (\fBesDMemHandle_T\fP *handle, size_t size)"
.br
.RI "\fIDodeljuje memorijski prostor velicine \fCsize\fP\&. \fP"
.ti -1c
.RI "void \fBesDMemDeAllocI\fP (\fBesDMemHandle_T\fP *handle, void *mem)"
.br
.RI "\fIReciklira memorijski prostor na koji pokazije \fCmem\fP pokazivac\&. \fP"
.ti -1c
.RI "void \fBesDMemDeAlloc\fP (\fBesDMemHandle_T\fP *handle, void *mem)"
.br
.RI "\fIReciklira memorijski prostor na koji pokazije \fCmem\fP pokazivac\&. \fP"
.ti -1c
.RI "void \fBesDMemUpdateStatusI\fP (\fBesDMemHandle_T\fP *handle, \fBesMemStatus_T\fP *status)"
.br
.RI "\fIVraca velicinu trenutno slobodne memorije u bajtovima\&. \fP"
.ti -1c
.RI "void \fBesDMemUpdateStatus\fP (\fBesDMemHandle_T\fP *handle, \fBesMemStatus_T\fP *status)"
.br
.RI "\fIVraca velicinu trenutno slobodne memorije u bajtovima\&. \fP"
.in -1c
.in -1c
.SS "Variables"

.PP
.RI "\fBDefault memory instance handles\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "\fBesSMemHandle_T\fP \fBDefSMemHandle\fP"
.br
.RI "\fIDefault static memory handle\&. \fP"
.ti -1c
.RI "\fBesPMemHandle_T\fP \fBDefPMemHandle\fP"
.br
.RI "\fIDefault pool memory handle\&. \fP"
.ti -1c
.RI "\fBesDMemHandle_T\fP \fBDefDMemHandle\fP"
.br
.RI "\fIDefault dynamic memory handle\&. \fP"
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
Memory Management API\&. 


.PP
\fBAuthor:\fP
.RS 4
Nenad Radulovic 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for eSolid - Memory Management from the source code\&.
