.TH "mem_cfg.h" 3 "Sat Nov 23 2013" "Version 1.0BetaR01" "eSolid - Memory Management" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mem_cfg.h \- 
.PP
Konfiguracija memorijskog menadzmenta\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.PP
.RI "\fBeSolid memory allocator override\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "#define \fBOPT_MEM_ALLOC\fP   malloc"
.br
.ti -1c
.RI "#define \fBOPT_MEM_FREE\fP   free"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
Konfiguracija memorijskog menadzmenta\&. 


.PP
\fBAuthor:\fP
.RS 4
Nenad Radulovic 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for eSolid - Memory Management from the source code\&.
