.TH "Configuration" 3 "Sat Nov 23 2013" "Version 1.0BetaR01" "eSolid - Memory Management" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Configuration \- 
.SS "eSolid memory allocator override"

.in +1c
.ti -1c
.RI "#define \fBOPT_MEM_ALLOC\fP   malloc"
.br
.ti -1c
.RI "#define \fBOPT_MEM_FREE\fP   free"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for eSolid - Memory Management from the source code\&.
