.TH "pMemBlock" 3 "Sat Nov 23 2013" "Version 1.0BetaR01" "eSolid - Memory Management" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pMemBlock \- 
.PP
Pool allocator header structure\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBpMemBlock\fP * \fBnext\fP"
.br
.RI "\fINext free block\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Pool allocator header structure\&. 
.SH "Field Documentation"
.PP 
.SS "struct \fBpMemBlock\fP* pMemBlock::next"

.PP
Next free block\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for eSolid - Memory Management from the source code\&.
